name: Test Ubuntu Setup

on:
  push:
    branches:
      - main

jobs:
  test-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run apt update and upgrade
      run: |
        sudo apt update -y 2>/dev/null | grep packages | cut -d '.' -f 1 && sudo apt upgrade -y 2>/dev/null | grep packages | cut -d '.' -f 1

    - name: Test git and gh installer
      run: |
        bash installer/git-and-gh.sh

    - name: Test ulauncher installer
      run: |
        bash installer/ulauncher.sh

    - name: Test alacarte installer
      run: |
        bash installer/alacarte.sh

    - name: Test Python39 and pip installer
      run: |
        bash installer/python39-deadsnake-and-pip.sh

    - name: Test Sublime Text 4 installer
      run: |
        bash installer/sublime-text.sh

    - name: Test Zoom installer
      run: |
        bash installer/zoom.sh

    - name: Test MySQL installer
      run: |
        bash installer/mysql.sh

    - name: Test Xapp installer
      run: |
        bash installer/xapp.sh

    - name: Test Docker installer
      run: |
        bash installer/docker-engine-and-desktop.sh

    - name: Run Apt List Test
      run: |
        bash .github/workflows/test_script/aptlist.sh
