name: Test Ubuntu Setup

on:
  push:
    branches:
      - main

jobs:
  test-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Install Test
      run: |
        bash ubuntu-setup/test_script/install.sh
        continue-on-error: true

    - name: Run Apt List Test
      run: |
        bash ubuntu-setup/test_script/aptlist.sh
        continue-on-error: true
