name: Test Ubuntu Setup

on:
  push:
    branches:
      - main

jobs:
  test-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Setup
      run: |
        git clone https://github.com/Krittipoom/ubuntu-setup.git
        bash ubuntu-setup/firstsetup.sh
        continue-on-error: true

    - name: Check Apt List
      run: |
        apt list alacarte
        apt list gh
        apt list git
        apt list mysql-client*
        apt list python3.9
        apt list sublime-text
        apt list ulauncher
        apt list vlc
        apt list xapp
        apt list zoom
        ls -al
